services:
    productsdb:
        image: mongo:latest
        ports:
            - "5001:27017"
    ratingsdb:
        image: mongo:latest
        ports:
            - "6001:27017"
    products:
        build: ./products
        ports:
            - "5000:5000"
        environment:
            - MONGODB_CONNECTION_STRING=mongodb://productsdb:27017/online-shop-products
            - PORT=5000
        depends_on:
            - productsdb
    ratings:
        build: ./ratings
        ports:
            - "6000:6000"
        environment:
            - MONGODB_CONNECTION_STRING=mongodb://ratingsdb:27017/online-shop-ratings
            - PORT=6000
        depends_on:
            - ratingsdb
