# Client Credential Flow

# see https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#get-a-token
# for details


# Tenant htl-villach.at
@tenantId=2b197efa-8e1b-4680-b263-8e237889b5b3

# Name of the registered app
@clientId=4769ca77-a9e9-45e2-b52c-e66f89f898cd

# The credential of the client = client_secret
@clientCredential=iFw8Q~-amqq3WMj2KDIJ28ZKIke.o.g09FpFdcbA

# What kind of authorizations are requested?
# @scope={{clientId}}/.default%20profile   - does not work
@scope={{clientId}}/.default



### Start Client Credentials flow

# @name authResult
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&scope={{scope}}&client_secret={{clientCredential}}&grant_type=client_credentials


### save response in variables

@accessToken = {{authResult.response.body.$.access_token}}


### Send request to own API using access token

GET http://127.0.0.1:8080/api/info
Authorization: Bearer {{accessToken}}

