# Resource Owner Password Credentials (ROPC)

# see https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth-ropc
# for details


# Tenant htl-villach.at
@tenantId=2b197efa-8e1b-4680-b263-8e237889b5b3

# Name of the registered app
@clientId=4769ca77-a9e9-45e2-b52c-e66f89f898cd

# The credential of the client
@username=kendlbat@edu.htl-villach.at


# Add you password here for testing purposes
@password=passwort1

# Huh wer hat da sei super sicheres Passwort in die repo committed?

# What kind of authorizations are requested?
@scope={{clientId}}/.default openid profile offline_access



### Resource Owner Password flow
# @name authResult
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&scope={{scope}}&username={{username}}&password={{password}}&grant_type=password


### save response in variables

@accessToken = {{authResult.response.body.$.access_token}}
@idToken = {{authResult.response.body.$.id_token}}
@refreshToken = {{authResult.response.body.$.refresh_token}}



### Send request to own API using access token

GET http://127.0.0.1:8080/api/info
Authorization: Bearer {{accessToken}}

